os: linux
dist: bionic
language: cpp

git:
  submodules: false

env:
  global:
  - SNAPCRAFT_ENABLE_ERROR_REPORTING=0
  - SNAPCRAFT_BUILD_INFO=1
  # regexes for release branch and tag
  - MULTIPASS_RELEASE_BRANCH_PATTERN="^release/([0-9\.]+)$"
  - MULTIPASS_RELEASE_TAG_PATTERN="^v([0-9]+\.[0-9]+)\.[0-9]+$"
  # build label added to the version string
  - MULTIPASS_BUILD_LABEL=""
  # whether to publish the built packages
  - MULTIPASS_PUBLISH=""
  # which channel to publish to
  - MULTIPASS_SNAP_CHANNEL=""
  # options to pass to the build reporter
  - MULTIPASS_REPORT_OPTIONS=()

stages:
- name: build
  if: | # bors and release branches, release tags and all pull requests
    (type = push
     AND (branch IN (staging, trying, master)
          OR branch ~= env(MULTIPASS_RELEASE_BRANCH_PATTERN)
          OR branch ~= env(MULTIPASS_RELEASE_TAG_PATTERN)))
    OR type = pull_request
- name: process snaps
  if: type = cron

jobs:
  include:
    - stage: build
      name: macOS
      env: BUILD_TYPE=macOS
      if: |
        repo = canonical/multipass
               AND (type != pull_request
                    OR head_repo = repo)

      before_install:
      - source tools/setup_build.sh
      - &decrypt-bot-data |
        openssl aes-256-cbc -K $encrypted_1b80fb3c7803_key -iv $encrypted_1b80fb3c7803_iv \
          -in tools/bot-data.tar.xz.enc -out tools/bot-data.tar.xz -d
        tar --extract --xz --file tools/bot-data.tar.xz --directory ${HOME}

      script:
      - |
        if [ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]; then
          REF="+refs/pull/${TRAVIS_PULL_REQUEST}/merge"
        else
          REF="${TRAVIS_COMMIT}"
        fi
        ARTIFACTS_DIR=$( ssh -q -p ${MAC_PORT} ${MAC_USERHOST} mktemp -d )
        ssh -q -p ${MAC_PORT} ${MAC_USERHOST} multipass-build/build-in-snapshot.sh public "${REF}" "${ARTIFACTS_DIR}" "${MULTIPASS_BUILD_LABEL}"
      after_success:
      - &python-requirements |
        pyenv local 3.8.1 && python3 -m pip install --requirement tools/requirements.txt boto3
      - scp -P ${MAC_PORT} ${MAC_USERHOST}:${ARTIFACTS_DIR}/*.pkg .
      - python3 -m tools.report_build "${MULTIPASS_REPORT_OPTIONS[@]}"
          --file *.pkg
          --s3-bucket multipass-ci
          --s3-prefix "${MULTIPASS_BUILD_LABEL}"
          macOS '[{filename}]({url})'

    - stage: process snaps
      name: Process snaps
      env: ~
      language: python
      python: 3.8

      addons:
        snaps:
        - review-tools

      before_install:
      - *decrypt-bot-data

      install:
      - *python-requirements

      script:
      - tools/process_snaps.py
