name: Build

on:
  push:
    branches:
    - master
    - staging
    - trying
    - release/[0-9]+.[0-9]+
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

jobs:
  Debug:
    runs-on: ubuntu-latest

    steps:
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1

    # Could use `use_lxd: true` above, but lxc/lxd-pkg-snap#63 makes it go stuck for 10 minutes.
    - name: Install LXD
      run: |
        sudo apt-get remove --purge --yes lxd lxd-client
        sudo snap install lxd
        sudo /snap/bin/lxd waitready
        sudo /snap/bin/lxd init --auto
        sudo usermod --append --groups lxd $USER

    - name: Check out code
      uses: actions/checkout@v2
      with:
        # Need to fetch it all for submodules to work.
        fetch-depth: 0

    - name: Check out submodules
      run: |
        git submodule sync
        # This repository can't do depth.
        git -c protocol.version=2 submodule update --init 3rd-party/xz-decoder/xz-embedded
        git -c protocol.version=2 submodule update --init --force --depth=1 --recursive

    - name: Fetch tags
      run: |
        git fetch --no-recurse-submodules origin +refs/tags/*:refs/tags/*

    - name: Patch
      run: |
        [ ! -f tests/travis.patch ] || patch -p1 --no-backup-if-mismatch < tests/travis.patch
        [ ! -f tests/travis-${{ github.job }}.patch ] || patch -p1 --no-backup-if-mismatch < tests/travis-${{ github.job }}.patch

    - name: Build
      run: |
        # Build the `multipass` part.
        sg lxd -c '/snap/bin/snapcraft build --use-lxd multipass'

    - name: Test
      run: |
        sg lxd -c '/snap/bin/lxc start snapcraft-multipass'
        sg lxd -c \
          '/snap/bin/lxc exec snapcraft-multipass -- \
             env CTEST_OUTPUT_ON_FAILURE=1 \
                 LD_LIBRARY_PATH=/root/stage/usr/lib/x86_64-linux-gnu/:/root/stage/lib/:/root/parts/multipass/build/lib/ \
                 /root/parts/multipass/build/bin/multipass_tests'
